### ISSUE TITLE
Configure org level issue labels standards

### ISSUE THREAD

**Issue by simcof** [OpenMined/.github#2]

**Comment by cereallarceny** [comment]
I'd like to migrate our labels to the following structure of hierarchy:

- Status
  - Abandoned
  - Available
  - Blocked
  - In Progress
  - Review Needed
  - Completed
- Type
  - Bug
  - Documentation
  - Improvement
  - New Feature
  - Refactor
- Priority
  - 4 - Critical
  - 3 - High
  - 2 - Medium
  - 1 - Low

This would mean that issues would be displayed like the following:
- "Status: Available"
- "Type: Documentation"
- "Priority: 2 - Medium"

This is roughly based on the following guide: https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63

**Comment by cereallarceny** [comment]
I'd also like to organize these by color and add emojis to provide a visual description as closely related as possible.

**Comment by Nolski** [comment]
To me, priority and severity seem fairly interlinked and might be a bit redundant. It might be worthwhile having a "Status: To Triage" or something of the sort in order to determine the other lables needed. A couple of other helpful lables I've found are:

 - Wontfix (is this abandoned?)
 - Research (should result in a new ticket being created)
 - Question (but perhaps we should discourage this)


I'm not sure they're super necessary given the list is already comprehensive but I figured I'd drop them here just in case.

**Comment by cereallarceny** [comment]
Priority and severity are inherently different. @simcof convinced me of this too. There's a difference between the importance of fixing an issue in a timely manner (priority) and how many parts of the codebase this issue affects (severity). Check out this chart for an explanation on how they're different: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSIf6OwCw0h-haE8uBDE6LMJKPgigEY6CbaVKCZMvrBNg89KsJn&usqp=CAU

- Wontfix - these issues can be closed because they're irrelevant. Abandoned means that we need to reassign something that's been claimed, but not done.
- Research we could do, I'll add that.
- Question I've added.
